//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Tue Jun 28 13:57:29 BST 2016
//
// Method conflict info:
// Method: bluetile_client_request_get
// Conflict-free: bluetile_client_response_put,
// 	       pin_gpio,
// 	       pin_timer,
// 	       pin_gpio_external
// Conflicts: bluetile_client_request_get
//
// Method: bluetile_client_response_put
// Conflict-free: bluetile_client_request_get,
// 	       pin_gpio,
// 	       pin_timer,
// 	       pin_gpio_external
// Conflicts: bluetile_client_response_put
//
// Method: pin_gpio
// Conflict-free: bluetile_client_request_get,
// 	       bluetile_client_response_put,
// 	       pin_gpio,
// 	       pin_timer,
// 	       pin_gpio_external
//
// Method: pin_timer
// Conflict-free: bluetile_client_request_get,
// 	       bluetile_client_response_put,
// 	       pin_gpio,
// 	       pin_gpio_external
// Sequenced before (restricted): pin_timer
//
// Method: pin_gpio_external
// Conflict-free: bluetile_client_request_get,
// 	       bluetile_client_response_put,
// 	       pin_gpio,
// 	       pin_timer
// Sequenced before (restricted): pin_gpio_external
//
//
// Ports:
// Name                         I/O  size props
// bluetile_client_request_get    O    32 reg
// RDY_bluetile_client_request_get  O     1 reg
// RDY_bluetile_client_response_put  O     1 reg
// pin_gpio                       O     8 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// bluetile_client_response_put   I    32 reg
// pin_timer_timer_external       I    32
// pin_gpio_external_gpio_external  I    32 reg
// EN_bluetile_client_response_put  I     1
// EN_bluetile_client_request_get  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkTop_level(CLK,
		   RST_N,

		   EN_bluetile_client_request_get,
		   bluetile_client_request_get,
		   RDY_bluetile_client_request_get,

		   bluetile_client_response_put,
		   EN_bluetile_client_response_put,
		   RDY_bluetile_client_response_put,

		   pin_gpio,

		   pin_timer_timer_external,

		   pin_gpio_external_gpio_external);
  input  CLK;
  input  RST_N;

  // actionvalue method bluetile_client_request_get
  input  EN_bluetile_client_request_get;
  output [31 : 0] bluetile_client_request_get;
  output RDY_bluetile_client_request_get;

  // action method bluetile_client_response_put
  input  [31 : 0] bluetile_client_response_put;
  input  EN_bluetile_client_response_put;
  output RDY_bluetile_client_response_put;

  // value method pin_gpio
  output [7 : 0] pin_gpio;

  // action method pin_timer
  input  [31 : 0] pin_timer_timer_external;

  // action method pin_gpio_external
  input  [31 : 0] pin_gpio_external_gpio_external;

  // signals for module outputs
  wire [31 : 0] bluetile_client_request_get;
  wire [7 : 0] pin_gpio;
  wire RDY_bluetile_client_request_get, RDY_bluetile_client_response_put;

  // ports of submodule cmd_m
  wire [31 : 0] cmd_m$bluetile_client_CMDQ_request_get,
		cmd_m$bluetile_client_CMDQ_response_put,
		cmd_m$bluetile_client_SUBCMDCPU_request_get,
		cmd_m$bluetile_client_SUBCMDCPU_response_put,
		cmd_m$bluetile_server_CMDQ_request_put,
		cmd_m$bluetile_server_CMDQ_response_get;
  wire cmd_m$EN_bluetile_client_CMDQ_request_get,
       cmd_m$EN_bluetile_client_CMDQ_response_put,
       cmd_m$EN_bluetile_client_SUBCMDCPU_request_get,
       cmd_m$EN_bluetile_client_SUBCMDCPU_response_put,
       cmd_m$EN_bluetile_server_CMDQ_request_put,
       cmd_m$EN_bluetile_server_CMDQ_response_get,
       cmd_m$RDY_bluetile_client_CMDQ_request_get,
       cmd_m$RDY_bluetile_client_CMDQ_response_put,
       cmd_m$RDY_bluetile_client_SUBCMDCPU_request_get,
       cmd_m$RDY_bluetile_client_SUBCMDCPU_response_put,
       cmd_m$RDY_bluetile_server_CMDQ_request_put,
       cmd_m$RDY_bluetile_server_CMDQ_response_get;

  // ports of submodule cmd_q
  wire [31 : 0] cmd_q$bluetile_client_CMDMEM_request_get,
		cmd_q$bluetile_client_CMDMEM_response_put,
		cmd_q$bluetile_client_HWMAN_request_get,
		cmd_q$bluetile_client_HWMAN_response_put,
		cmd_q$bluetile_server_CMDMEM_request_put,
		cmd_q$bluetile_server_CMDMEM_response_get,
		cmd_q$bluetile_server_CMDPROCESSOR_request_put,
		cmd_q$bluetile_server_CMDPROCESSOR_response_get,
		cmd_q$bluetile_server_HWMAN_request_put,
		cmd_q$bluetile_server_HWMAN_response_get,
		cmd_q$pin_gpio_external_gpio_external,
		cmd_q$pin_timer_timer_external;
  wire cmd_q$EN_bluetile_client_CMDMEM_request_get,
       cmd_q$EN_bluetile_client_CMDMEM_response_put,
       cmd_q$EN_bluetile_client_HWMAN_request_get,
       cmd_q$EN_bluetile_client_HWMAN_response_put,
       cmd_q$EN_bluetile_server_CMDMEM_request_put,
       cmd_q$EN_bluetile_server_CMDMEM_response_get,
       cmd_q$EN_bluetile_server_CMDPROCESSOR_request_put,
       cmd_q$EN_bluetile_server_CMDPROCESSOR_response_get,
       cmd_q$EN_bluetile_server_HWMAN_request_put,
       cmd_q$EN_bluetile_server_HWMAN_response_get,
       cmd_q$EN_pin_gpio_external,
       cmd_q$EN_pin_timer,
       cmd_q$RDY_bluetile_client_CMDMEM_request_get,
       cmd_q$RDY_bluetile_client_CMDMEM_response_put,
       cmd_q$RDY_bluetile_client_HWMAN_request_get,
       cmd_q$RDY_bluetile_client_HWMAN_response_put,
       cmd_q$RDY_bluetile_server_CMDMEM_request_put,
       cmd_q$RDY_bluetile_server_CMDMEM_response_get,
       cmd_q$RDY_bluetile_server_CMDPROCESSOR_request_put,
       cmd_q$RDY_bluetile_server_CMDPROCESSOR_response_get,
       cmd_q$RDY_bluetile_server_HWMAN_request_put,
       cmd_q$RDY_bluetile_server_HWMAN_response_get;

  // ports of submodule cmd_u
  wire [31 : 0] cmd_u$bluetile_client_hw_man_request_get,
		cmd_u$bluetile_client_hw_man_response_put,
		cmd_u$bluetile_client_request_get,
		cmd_u$bluetile_client_response_put,
		cmd_u$pin_gpio,
		cmd_u$pin_gpio_cmd_q,
		cmd_u$pin_gpio_external_gpio_external;
  wire cmd_u$EN_bluetile_client_hw_man_request_get,
       cmd_u$EN_bluetile_client_hw_man_response_put,
       cmd_u$EN_bluetile_client_request_get,
       cmd_u$EN_bluetile_client_response_put,
       cmd_u$EN_pin_gpio_external,
       cmd_u$RDY_bluetile_client_hw_man_request_get,
       cmd_u$RDY_bluetile_client_hw_man_response_put,
       cmd_u$RDY_bluetile_client_request_get,
       cmd_u$RDY_bluetile_client_response_put;

  // ports of submodule hw_manager
  wire [31 : 0] hw_manager$bluetile_client_CMDQ_request_get,
		hw_manager$bluetile_client_CMDQ_response_put,
		hw_manager$bluetile_client_request_get,
		hw_manager$bluetile_client_response_put,
		hw_manager$bluetile_server_CMDPROCESSOR_request_put,
		hw_manager$bluetile_server_CMDPROCESSOR_response_get,
		hw_manager$bluetile_server_CMDQ_request_put,
		hw_manager$bluetile_server_CMDQ_response_get,
		hw_manager$bluetile_server_SUBCMDCPU_request_put,
		hw_manager$bluetile_server_SUBCMDCPU_response_get;
  wire hw_manager$EN_bluetile_client_CMDQ_request_get,
       hw_manager$EN_bluetile_client_CMDQ_response_put,
       hw_manager$EN_bluetile_client_request_get,
       hw_manager$EN_bluetile_client_response_put,
       hw_manager$EN_bluetile_server_CMDPROCESSOR_request_put,
       hw_manager$EN_bluetile_server_CMDPROCESSOR_response_get,
       hw_manager$EN_bluetile_server_CMDQ_request_put,
       hw_manager$EN_bluetile_server_CMDQ_response_get,
       hw_manager$EN_bluetile_server_SUBCMDCPU_request_put,
       hw_manager$EN_bluetile_server_SUBCMDCPU_response_get,
       hw_manager$RDY_bluetile_client_CMDQ_request_get,
       hw_manager$RDY_bluetile_client_CMDQ_response_put,
       hw_manager$RDY_bluetile_client_request_get,
       hw_manager$RDY_bluetile_client_response_put,
       hw_manager$RDY_bluetile_server_CMDPROCESSOR_request_put,
       hw_manager$RDY_bluetile_server_CMDPROCESSOR_response_get,
       hw_manager$RDY_bluetile_server_CMDQ_request_put,
       hw_manager$RDY_bluetile_server_CMDQ_response_get,
       hw_manager$RDY_bluetile_server_SUBCMDCPU_request_put,
       hw_manager$RDY_bluetile_server_SUBCMDCPU_response_get;

  // actionvalue method bluetile_client_request_get
  assign bluetile_client_request_get =
	     hw_manager$bluetile_client_request_get ;
  assign RDY_bluetile_client_request_get =
	     hw_manager$RDY_bluetile_client_request_get ;

  // action method bluetile_client_response_put
  assign RDY_bluetile_client_response_put =
	     hw_manager$RDY_bluetile_client_response_put ;

  // value method pin_gpio
  assign pin_gpio = cmd_u$pin_gpio[31:24] ;

  // submodule cmd_m
  mkGPIOCMD_cmd_memory cmd_m(.CLK(CLK),
			     .RST_N(RST_N),
			     .bluetile_client_CMDQ_response_put(cmd_m$bluetile_client_CMDQ_response_put),
			     .bluetile_client_SUBCMDCPU_response_put(cmd_m$bluetile_client_SUBCMDCPU_response_put),
			     .bluetile_server_CMDQ_request_put(cmd_m$bluetile_server_CMDQ_request_put),
			     .EN_bluetile_client_SUBCMDCPU_request_get(cmd_m$EN_bluetile_client_SUBCMDCPU_request_get),
			     .EN_bluetile_client_SUBCMDCPU_response_put(cmd_m$EN_bluetile_client_SUBCMDCPU_response_put),
			     .EN_bluetile_client_CMDQ_request_get(cmd_m$EN_bluetile_client_CMDQ_request_get),
			     .EN_bluetile_client_CMDQ_response_put(cmd_m$EN_bluetile_client_CMDQ_response_put),
			     .EN_bluetile_server_CMDQ_request_put(cmd_m$EN_bluetile_server_CMDQ_request_put),
			     .EN_bluetile_server_CMDQ_response_get(cmd_m$EN_bluetile_server_CMDQ_response_get),
			     .bluetile_client_SUBCMDCPU_request_get(cmd_m$bluetile_client_SUBCMDCPU_request_get),
			     .RDY_bluetile_client_SUBCMDCPU_request_get(cmd_m$RDY_bluetile_client_SUBCMDCPU_request_get),
			     .RDY_bluetile_client_SUBCMDCPU_response_put(cmd_m$RDY_bluetile_client_SUBCMDCPU_response_put),
			     .bluetile_client_CMDQ_request_get(cmd_m$bluetile_client_CMDQ_request_get),
			     .RDY_bluetile_client_CMDQ_request_get(cmd_m$RDY_bluetile_client_CMDQ_request_get),
			     .RDY_bluetile_client_CMDQ_response_put(cmd_m$RDY_bluetile_client_CMDQ_response_put),
			     .RDY_bluetile_server_CMDQ_request_put(cmd_m$RDY_bluetile_server_CMDQ_request_put),
			     .bluetile_server_CMDQ_response_get(cmd_m$bluetile_server_CMDQ_response_get),
			     .RDY_bluetile_server_CMDQ_response_get(cmd_m$RDY_bluetile_server_CMDQ_response_get));

  // submodule cmd_q
  mkGPIOCMD_cmd_q cmd_q(.CLK(CLK),
			.RST_N(RST_N),
			.bluetile_client_CMDMEM_response_put(cmd_q$bluetile_client_CMDMEM_response_put),
			.bluetile_client_HWMAN_response_put(cmd_q$bluetile_client_HWMAN_response_put),
			.bluetile_server_CMDMEM_request_put(cmd_q$bluetile_server_CMDMEM_request_put),
			.bluetile_server_CMDPROCESSOR_request_put(cmd_q$bluetile_server_CMDPROCESSOR_request_put),
			.bluetile_server_HWMAN_request_put(cmd_q$bluetile_server_HWMAN_request_put),
			.pin_gpio_external_gpio_external(cmd_q$pin_gpio_external_gpio_external),
			.pin_timer_timer_external(cmd_q$pin_timer_timer_external),
			.EN_bluetile_client_HWMAN_request_get(cmd_q$EN_bluetile_client_HWMAN_request_get),
			.EN_bluetile_client_HWMAN_response_put(cmd_q$EN_bluetile_client_HWMAN_response_put),
			.EN_bluetile_server_HWMAN_request_put(cmd_q$EN_bluetile_server_HWMAN_request_put),
			.EN_bluetile_server_HWMAN_response_get(cmd_q$EN_bluetile_server_HWMAN_response_get),
			.EN_bluetile_client_CMDMEM_request_get(cmd_q$EN_bluetile_client_CMDMEM_request_get),
			.EN_bluetile_client_CMDMEM_response_put(cmd_q$EN_bluetile_client_CMDMEM_response_put),
			.EN_bluetile_server_CMDMEM_request_put(cmd_q$EN_bluetile_server_CMDMEM_request_put),
			.EN_bluetile_server_CMDMEM_response_get(cmd_q$EN_bluetile_server_CMDMEM_response_get),
			.EN_bluetile_server_CMDPROCESSOR_request_put(cmd_q$EN_bluetile_server_CMDPROCESSOR_request_put),
			.EN_bluetile_server_CMDPROCESSOR_response_get(cmd_q$EN_bluetile_server_CMDPROCESSOR_response_get),
			.EN_pin_timer(cmd_q$EN_pin_timer),
			.EN_pin_gpio_external(cmd_q$EN_pin_gpio_external),
			.bluetile_client_HWMAN_request_get(cmd_q$bluetile_client_HWMAN_request_get),
			.RDY_bluetile_client_HWMAN_request_get(cmd_q$RDY_bluetile_client_HWMAN_request_get),
			.RDY_bluetile_client_HWMAN_response_put(cmd_q$RDY_bluetile_client_HWMAN_response_put),
			.RDY_bluetile_server_HWMAN_request_put(cmd_q$RDY_bluetile_server_HWMAN_request_put),
			.bluetile_server_HWMAN_response_get(cmd_q$bluetile_server_HWMAN_response_get),
			.RDY_bluetile_server_HWMAN_response_get(cmd_q$RDY_bluetile_server_HWMAN_response_get),
			.bluetile_client_CMDMEM_request_get(cmd_q$bluetile_client_CMDMEM_request_get),
			.RDY_bluetile_client_CMDMEM_request_get(cmd_q$RDY_bluetile_client_CMDMEM_request_get),
			.RDY_bluetile_client_CMDMEM_response_put(cmd_q$RDY_bluetile_client_CMDMEM_response_put),
			.RDY_bluetile_server_CMDMEM_request_put(cmd_q$RDY_bluetile_server_CMDMEM_request_put),
			.bluetile_server_CMDMEM_response_get(cmd_q$bluetile_server_CMDMEM_response_get),
			.RDY_bluetile_server_CMDMEM_response_get(cmd_q$RDY_bluetile_server_CMDMEM_response_get),
			.RDY_bluetile_server_CMDPROCESSOR_request_put(cmd_q$RDY_bluetile_server_CMDPROCESSOR_request_put),
			.bluetile_server_CMDPROCESSOR_response_get(cmd_q$bluetile_server_CMDPROCESSOR_response_get),
			.RDY_bluetile_server_CMDPROCESSOR_response_get(cmd_q$RDY_bluetile_server_CMDPROCESSOR_response_get),
			.RDY_pin_timer(),
			.RDY_pin_gpio_external());

  // submodule cmd_u
  mkGPIOCMD_cmd_processor cmd_u(.CLK(CLK),
				.RST_N(RST_N),
				.bluetile_client_hw_man_response_put(cmd_u$bluetile_client_hw_man_response_put),
				.bluetile_client_response_put(cmd_u$bluetile_client_response_put),
				.pin_gpio_external_gpio_external(cmd_u$pin_gpio_external_gpio_external),
				.EN_bluetile_client_request_get(cmd_u$EN_bluetile_client_request_get),
				.EN_bluetile_client_response_put(cmd_u$EN_bluetile_client_response_put),
				.EN_bluetile_client_hw_man_request_get(cmd_u$EN_bluetile_client_hw_man_request_get),
				.EN_bluetile_client_hw_man_response_put(cmd_u$EN_bluetile_client_hw_man_response_put),
				.EN_pin_gpio_external(cmd_u$EN_pin_gpio_external),
				.bluetile_client_request_get(cmd_u$bluetile_client_request_get),
				.RDY_bluetile_client_request_get(cmd_u$RDY_bluetile_client_request_get),
				.RDY_bluetile_client_response_put(cmd_u$RDY_bluetile_client_response_put),
				.bluetile_client_hw_man_request_get(cmd_u$bluetile_client_hw_man_request_get),
				.RDY_bluetile_client_hw_man_request_get(cmd_u$RDY_bluetile_client_hw_man_request_get),
				.RDY_bluetile_client_hw_man_response_put(cmd_u$RDY_bluetile_client_hw_man_response_put),
				.pin_gpio(cmd_u$pin_gpio),
				.RDY_pin_gpio(),
				.pin_gpio_cmd_q(cmd_u$pin_gpio_cmd_q),
				.RDY_pin_gpio_cmd_q(),
				.RDY_pin_gpio_external());

  // submodule hw_manager
  mkGPIOCMD_hw_manager hw_manager(.CLK(CLK),
				  .RST_N(RST_N),
				  .bluetile_client_CMDQ_response_put(hw_manager$bluetile_client_CMDQ_response_put),
				  .bluetile_client_response_put(hw_manager$bluetile_client_response_put),
				  .bluetile_server_CMDPROCESSOR_request_put(hw_manager$bluetile_server_CMDPROCESSOR_request_put),
				  .bluetile_server_CMDQ_request_put(hw_manager$bluetile_server_CMDQ_request_put),
				  .bluetile_server_SUBCMDCPU_request_put(hw_manager$bluetile_server_SUBCMDCPU_request_put),
				  .EN_bluetile_client_request_get(hw_manager$EN_bluetile_client_request_get),
				  .EN_bluetile_client_response_put(hw_manager$EN_bluetile_client_response_put),
				  .EN_bluetile_server_SUBCMDCPU_request_put(hw_manager$EN_bluetile_server_SUBCMDCPU_request_put),
				  .EN_bluetile_server_SUBCMDCPU_response_get(hw_manager$EN_bluetile_server_SUBCMDCPU_response_get),
				  .EN_bluetile_server_CMDQ_request_put(hw_manager$EN_bluetile_server_CMDQ_request_put),
				  .EN_bluetile_server_CMDQ_response_get(hw_manager$EN_bluetile_server_CMDQ_response_get),
				  .EN_bluetile_server_CMDPROCESSOR_request_put(hw_manager$EN_bluetile_server_CMDPROCESSOR_request_put),
				  .EN_bluetile_server_CMDPROCESSOR_response_get(hw_manager$EN_bluetile_server_CMDPROCESSOR_response_get),
				  .EN_bluetile_client_CMDQ_request_get(hw_manager$EN_bluetile_client_CMDQ_request_get),
				  .EN_bluetile_client_CMDQ_response_put(hw_manager$EN_bluetile_client_CMDQ_response_put),
				  .bluetile_client_request_get(hw_manager$bluetile_client_request_get),
				  .RDY_bluetile_client_request_get(hw_manager$RDY_bluetile_client_request_get),
				  .RDY_bluetile_client_response_put(hw_manager$RDY_bluetile_client_response_put),
				  .RDY_bluetile_server_SUBCMDCPU_request_put(hw_manager$RDY_bluetile_server_SUBCMDCPU_request_put),
				  .bluetile_server_SUBCMDCPU_response_get(hw_manager$bluetile_server_SUBCMDCPU_response_get),
				  .RDY_bluetile_server_SUBCMDCPU_response_get(hw_manager$RDY_bluetile_server_SUBCMDCPU_response_get),
				  .RDY_bluetile_server_CMDQ_request_put(hw_manager$RDY_bluetile_server_CMDQ_request_put),
				  .bluetile_server_CMDQ_response_get(hw_manager$bluetile_server_CMDQ_response_get),
				  .RDY_bluetile_server_CMDQ_response_get(hw_manager$RDY_bluetile_server_CMDQ_response_get),
				  .RDY_bluetile_server_CMDPROCESSOR_request_put(hw_manager$RDY_bluetile_server_CMDPROCESSOR_request_put),
				  .bluetile_server_CMDPROCESSOR_response_get(hw_manager$bluetile_server_CMDPROCESSOR_response_get),
				  .RDY_bluetile_server_CMDPROCESSOR_response_get(hw_manager$RDY_bluetile_server_CMDPROCESSOR_response_get),
				  .bluetile_client_CMDQ_request_get(hw_manager$bluetile_client_CMDQ_request_get),
				  .RDY_bluetile_client_CMDQ_request_get(hw_manager$RDY_bluetile_client_CMDQ_request_get),
				  .RDY_bluetile_client_CMDQ_response_put(hw_manager$RDY_bluetile_client_CMDQ_response_put));

  // submodule cmd_m
  assign cmd_m$bluetile_client_CMDQ_response_put =
	     cmd_q$bluetile_server_CMDMEM_response_get ;
  assign cmd_m$bluetile_client_SUBCMDCPU_response_put =
	     hw_manager$bluetile_server_SUBCMDCPU_response_get ;
  assign cmd_m$bluetile_server_CMDQ_request_put =
	     cmd_q$bluetile_client_CMDMEM_request_get ;
  assign cmd_m$EN_bluetile_client_SUBCMDCPU_request_get =
	     cmd_m$RDY_bluetile_client_SUBCMDCPU_request_get &&
	     hw_manager$RDY_bluetile_server_SUBCMDCPU_request_put ;
  assign cmd_m$EN_bluetile_client_SUBCMDCPU_response_put =
	     cmd_m$RDY_bluetile_client_SUBCMDCPU_response_put &&
	     hw_manager$RDY_bluetile_server_SUBCMDCPU_response_get ;
  assign cmd_m$EN_bluetile_client_CMDQ_request_get =
	     cmd_m$RDY_bluetile_client_CMDQ_request_get &&
	     cmd_q$RDY_bluetile_server_CMDMEM_request_put ;
  assign cmd_m$EN_bluetile_client_CMDQ_response_put =
	     cmd_m$RDY_bluetile_client_CMDQ_response_put &&
	     cmd_q$RDY_bluetile_server_CMDMEM_response_get ;
  assign cmd_m$EN_bluetile_server_CMDQ_request_put =
	     cmd_m$RDY_bluetile_server_CMDQ_request_put &&
	     cmd_q$RDY_bluetile_client_CMDMEM_request_get ;
  assign cmd_m$EN_bluetile_server_CMDQ_response_get =
	     cmd_m$RDY_bluetile_server_CMDQ_response_get &&
	     cmd_q$RDY_bluetile_client_CMDMEM_response_put ;

  // submodule cmd_q
  assign cmd_q$bluetile_client_CMDMEM_response_put =
	     cmd_m$bluetile_server_CMDQ_response_get ;
  assign cmd_q$bluetile_client_HWMAN_response_put =
	     hw_manager$bluetile_server_CMDQ_response_get ;
  assign cmd_q$bluetile_server_CMDMEM_request_put =
	     cmd_m$bluetile_client_CMDQ_request_get ;
  assign cmd_q$bluetile_server_CMDPROCESSOR_request_put =
	     cmd_u$bluetile_client_request_get ;
  assign cmd_q$bluetile_server_HWMAN_request_put =
	     hw_manager$bluetile_client_CMDQ_request_get ;
  assign cmd_q$pin_gpio_external_gpio_external = cmd_u$pin_gpio_cmd_q ;
  assign cmd_q$pin_timer_timer_external = pin_timer_timer_external ;
  assign cmd_q$EN_bluetile_client_HWMAN_request_get =
	     hw_manager$RDY_bluetile_server_CMDQ_request_put &&
	     cmd_q$RDY_bluetile_client_HWMAN_request_get ;
  assign cmd_q$EN_bluetile_client_HWMAN_response_put =
	     hw_manager$RDY_bluetile_server_CMDQ_response_get &&
	     cmd_q$RDY_bluetile_client_HWMAN_response_put ;
  assign cmd_q$EN_bluetile_server_HWMAN_request_put =
	     hw_manager$RDY_bluetile_client_CMDQ_request_get &&
	     cmd_q$RDY_bluetile_server_HWMAN_request_put ;
  assign cmd_q$EN_bluetile_server_HWMAN_response_get =
	     hw_manager$RDY_bluetile_client_CMDQ_response_put &&
	     cmd_q$RDY_bluetile_server_HWMAN_response_get ;
  assign cmd_q$EN_bluetile_client_CMDMEM_request_get =
	     cmd_m$RDY_bluetile_server_CMDQ_request_put &&
	     cmd_q$RDY_bluetile_client_CMDMEM_request_get ;
  assign cmd_q$EN_bluetile_client_CMDMEM_response_put =
	     cmd_m$RDY_bluetile_server_CMDQ_response_get &&
	     cmd_q$RDY_bluetile_client_CMDMEM_response_put ;
  assign cmd_q$EN_bluetile_server_CMDMEM_request_put =
	     cmd_m$RDY_bluetile_client_CMDQ_request_get &&
	     cmd_q$RDY_bluetile_server_CMDMEM_request_put ;
  assign cmd_q$EN_bluetile_server_CMDMEM_response_get =
	     cmd_m$RDY_bluetile_client_CMDQ_response_put &&
	     cmd_q$RDY_bluetile_server_CMDMEM_response_get ;
  assign cmd_q$EN_bluetile_server_CMDPROCESSOR_request_put =
	     cmd_u$RDY_bluetile_client_request_get &&
	     cmd_q$RDY_bluetile_server_CMDPROCESSOR_request_put ;
  assign cmd_q$EN_bluetile_server_CMDPROCESSOR_response_get =
	     cmd_u$RDY_bluetile_client_response_put &&
	     cmd_q$RDY_bluetile_server_CMDPROCESSOR_response_get ;
  assign cmd_q$EN_pin_timer = 1'd1 ;
  assign cmd_q$EN_pin_gpio_external = 1'd1 ;

  // submodule cmd_u
  assign cmd_u$bluetile_client_hw_man_response_put =
	     hw_manager$bluetile_server_CMDPROCESSOR_response_get ;
  assign cmd_u$bluetile_client_response_put =
	     cmd_q$bluetile_server_CMDPROCESSOR_response_get ;
  assign cmd_u$pin_gpio_external_gpio_external =
	     pin_gpio_external_gpio_external ;
  assign cmd_u$EN_bluetile_client_request_get =
	     cmd_u$RDY_bluetile_client_request_get &&
	     cmd_q$RDY_bluetile_server_CMDPROCESSOR_request_put ;
  assign cmd_u$EN_bluetile_client_response_put =
	     cmd_u$RDY_bluetile_client_response_put &&
	     cmd_q$RDY_bluetile_server_CMDPROCESSOR_response_get ;
  assign cmd_u$EN_bluetile_client_hw_man_request_get =
	     cmd_u$RDY_bluetile_client_hw_man_request_get &&
	     hw_manager$RDY_bluetile_server_CMDPROCESSOR_request_put ;
  assign cmd_u$EN_bluetile_client_hw_man_response_put =
	     cmd_u$RDY_bluetile_client_hw_man_response_put &&
	     hw_manager$RDY_bluetile_server_CMDPROCESSOR_response_get ;
  assign cmd_u$EN_pin_gpio_external = 1'd1 ;

  // submodule hw_manager
  assign hw_manager$bluetile_client_CMDQ_response_put =
	     cmd_q$bluetile_server_HWMAN_response_get ;
  assign hw_manager$bluetile_client_response_put =
	     bluetile_client_response_put ;
  assign hw_manager$bluetile_server_CMDPROCESSOR_request_put =
	     cmd_u$bluetile_client_hw_man_request_get ;
  assign hw_manager$bluetile_server_CMDQ_request_put =
	     cmd_q$bluetile_client_HWMAN_request_get ;
  assign hw_manager$bluetile_server_SUBCMDCPU_request_put =
	     cmd_m$bluetile_client_SUBCMDCPU_request_get ;
  assign hw_manager$EN_bluetile_client_request_get =
	     EN_bluetile_client_request_get ;
  assign hw_manager$EN_bluetile_client_response_put =
	     EN_bluetile_client_response_put ;
  assign hw_manager$EN_bluetile_server_SUBCMDCPU_request_put =
	     cmd_m$RDY_bluetile_client_SUBCMDCPU_request_get &&
	     hw_manager$RDY_bluetile_server_SUBCMDCPU_request_put ;
  assign hw_manager$EN_bluetile_server_SUBCMDCPU_response_get =
	     cmd_m$RDY_bluetile_client_SUBCMDCPU_response_put &&
	     hw_manager$RDY_bluetile_server_SUBCMDCPU_response_get ;
  assign hw_manager$EN_bluetile_server_CMDQ_request_put =
	     hw_manager$RDY_bluetile_server_CMDQ_request_put &&
	     cmd_q$RDY_bluetile_client_HWMAN_request_get ;
  assign hw_manager$EN_bluetile_server_CMDQ_response_get =
	     hw_manager$RDY_bluetile_server_CMDQ_response_get &&
	     cmd_q$RDY_bluetile_client_HWMAN_response_put ;
  assign hw_manager$EN_bluetile_server_CMDPROCESSOR_request_put =
	     cmd_u$RDY_bluetile_client_hw_man_request_get &&
	     hw_manager$RDY_bluetile_server_CMDPROCESSOR_request_put ;
  assign hw_manager$EN_bluetile_server_CMDPROCESSOR_response_get =
	     cmd_u$RDY_bluetile_client_hw_man_response_put &&
	     hw_manager$RDY_bluetile_server_CMDPROCESSOR_response_get ;
  assign hw_manager$EN_bluetile_client_CMDQ_request_get =
	     hw_manager$RDY_bluetile_client_CMDQ_request_get &&
	     cmd_q$RDY_bluetile_server_HWMAN_request_put ;
  assign hw_manager$EN_bluetile_client_CMDQ_response_put =
	     hw_manager$RDY_bluetile_client_CMDQ_response_put &&
	     cmd_q$RDY_bluetile_server_HWMAN_response_get ;
endmodule  // mkTop_level

